name: sync_to_gitgud

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://gitgud.io/StageDog/tavern_resource.git
          username: StageDog
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
