name: webpack

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with: { version: 10 }
      - run: pnpm i
      - run: pnpm build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Webpack'
